### ISSUE TITLE
Crashing on loading to a heist

### ISSUE THREAD

**Issue by kriszhun25** [pierre-josselin/payday-2-ultimate-trainer-5#103]
Hi, my game is crashing loading to a heist, 
[crash.txt](https://github.com/pierre-josselin/payday-2-ultimate-trainer-5/files/10833510/crash.txt)

**Comment by AlexanderQueen** [comment]
Same history. Clean install.

**Comment by pierre-josselin** [comment]
Hello, since in the crashlog there is no reference to this mod and this mod does not hook the mentioned files I would tend to think that the crash would not come from this mod but from another mod or of a conflict with another mod.

Also, crashes could happen when loading the heist if you had changed the weather (time menu). You can reset it from the main menu.

If the problem persists, you can try to install the latest stable version ([5.3.0](https://github.com/pierre-josselin/payday-2-ultimate-trainer-5/releases/tag/5.3.0) from June 2022) rather than the development version (main).

Since I'm no longer actively working on this mod I couldn't help you more but I'll leave the issue open if anyone has a solution.

**Comment by pierre-josselin** [comment]
Closed as Ultimate Trainer 6 is released:
https://github.com/pierre-josselin/payday-2-ultimate-trainer-6
